language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get install -y libglu1-mesa libgles2-mesa-dev libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev libglu-dev libglew-dev libsdl2-dev 
install:
    - curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz | tar xvz -C ..
 
script:
    - ../premake5 gmake
    - make
