# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  SurfaceProgram_config = debug
endif
ifeq ($(config),release)
  SurfaceProgram_config = release
endif

PROJECTS := SurfaceProgram

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SurfaceProgram:
ifneq (,$(SurfaceProgram_config))
	@echo "==== Building SurfaceProgram ($(SurfaceProgram_config)) ===="
	@${MAKE} --no-print-directory -C . -f SurfaceProgram.make config=$(SurfaceProgram_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f SurfaceProgram.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SurfaceProgram"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"